[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  skip_processing = true

# SPA Redirect (all paths -> index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers (e.g., security/CORS)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"